[build]
builder = "nixpacks"

[deploy]
startCommand = "FLASK_APP=run.py flask db upgrade && python seed.py && gunicorn --bind 0.0.0.0:$PORT run:app"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
